### ISSUE TITLE
Cannot kill Dude

### ISSUE THREAD

**Issue by bjowes** [TheGrandmother/cwg#18]
Tried to kill the Dude with laser, did not work. The player and the dude where hit by the laser but only points for the player were counted and the dude didn't die.

**Comment by TheGrandmother** [comment]
I can't reproduce this.

Did you hit your self or the other player with the laser?

Are you sure that the dude didn't avoid the laser? I.e that it moved away from the square where the laser was in the same step as you fired the laser?

**Comment by bjowes** [comment]
After some more testing I think the issue is that when I try to kill the dude with the laser, if I fire it one round too late, it looks like it hits (since it is drawn instantly) but it misses since the dude is moving to another square. When I fire in the square the dude move to it is killed. Maybe laser should be drawn a bit later - like halfway into the round?

**Comment by TheGrandmother** [comment]
Fixed!
