### ISSUE TITLE
Points when killing dude looks strange

### ISSUE THREAD

**Issue by bjowes** [TheGrandmother/cwg#23]
I got "+-3" points shown when I killed the dude. Either the opponent should be given +3, or I should get only -3. Earlier there was a policy that all points should be positive, but I think we can allow negative points too as long as they can be counted and shown properly. We should then also change how points are awarded when a tank kills itself, gets a gas mask and so on.

**Comment by bjowes** [comment]
Tried it again with the redeemer, and got both "+2" and "+-3"??

**Comment by bjowes** [comment]
Tried again, got "+-2"

**Comment by TheGrandmother** [comment]
Changed it so that it only uses positive scores. I haven't been able to reproduce the error now so I assume it is fixed.
