### ISSUE TITLE
Missing opponent with redeemer

### ISSUE THREAD

**Issue by bjowes** [TheGrandmother/cwg#24]
When firing the redeemer just one square away from the opponent, it flies over the opponent and explodes after the opponent, leaving the opponent alive. Should explode on contact and kill both tanks.

**Comment by TheGrandmother** [comment]
Redeemers does not explode with tanks on contact by design.
Just thought it would be more fun to have the redeemers be only time controlled.

but if you want to i could change that so redeemers explode on collision.

**Comment by bjowes** [comment]
Ok, that makes it more clear. Keep as is!

**Comment by TheGrandmother** [comment]
Kalawesome!
