### ISSUE TITLE
Engine crash

### ISSUE THREAD

**Issue by bjowes** [TheGrandmother/cwg#29]
Run this board with dumb player against powerup player to reproduce. Occurs when player and redeemer exits board.

cwg15@cwg15-Team ~ $ cat engine_crash.txt 
x....p...$t...
..$.ptx..$.dxx
.x..x$xpx.xx..
p........x....
$x...$.x.p.x..
.l$..xs...$...
x..x.p........
x.....x$.$$.x.
.xpx.$.x.....x
x..p........r.
...x.x.$x...p.
.x....p$.x....

**Comment by TheGrandmother** [comment]
Fixed!

This bug was introduced when redeemers started exploding when colliding with walls.
Problem was that redeemer was removed when it moved of the board but it tried to decrement the timer after it had moved.
