### ISSUE TITLE
Invisible redeemer explosion

### ISSUE THREAD

**Issue by bjowes** [TheGrandmother/cwg#30]
Run the board below with dumb and powerup players. When the powerup player fires the redeemer it explodes but no big explosion is shown.

cwg15@cwg15-Team ~ $ cat missing_explosion.txt 
.x...x..xx
x.s..x....
t..x.x.x$x
lp..x...p.
...xxx.x.$
$.p.x..p$x
xxx.xtdx..
.x$$p$xr..
xx...x....
.x.xx..xxp
..x..xp.xx
x.$p.p.xx.

**Comment by TheGrandmother** [comment]
Fixed.
Although I'm not really sure why it happened in the first place.....
